version: '2'

services:
    zookeeper:
        network_mode: host
        image: zookeeper:3.5
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"

    master:
        image: mesosphere/mesos-master:1.5.0
        network_mode: host
        ports:
            - "5050:5050"
        environment:
            MESOS_HOSTNAME: 0.0.0.0
            MESOS_IP: 0.0.0.0
            MESOS_ZK: zk://0.0.0.0:2181/mesos
            MESOS_PORT: 5050
            MESOS_LOG_DIR: /var/log/mesos
            MESOS_QUORUM: 1
            MESOS_REGISTRY: in_memory
            MESOS_WORK_DIR: /var/lib/mesos
            
    slave:
        network_mode: host
        image: mesosphere/mesos-slave:1.5.0
        environment:
            MESOS_MASTER: zk://0.0.0.0:2181/mesos
            MESOS_LOGGING_LEVEL: INFO
            MESOS_WORK_DIR: /var/lib/mesos
